### ISSUE TITLE
Unable to get camera URL with 2023.8.2

### ISSUE THREAD

**Issue by dmascord** [felipecrs/hass-expose-camera-stream-source#11]
Unsure whether this is a problem with my setup, but it looks like HomeAssistant is no longer returning the camera URL via the supervisor API:

core/info returns fine:
```
curl -fsSL -H "Authorization: Bearer ${SUPERVISOR_TOKEN}" "http://supervisor/core/info"
{"result": "ok", "data": {"version": "2023.8.2", "version_latest": "2023.8.2", "update_available": false, "machine": "qemux86-64", "ip_address": "172.30.32.1", "arch": "amd64", "image": "ghcr.io/home-assistant/qemux86-64-homeassistant", "boot": true, "port": 8123, "ssl": false, "watchdog": true, "audio_input": null, "audio_output": null}}
```

Any core/api calls return with 401:
```
[core-ssh config]$ curl -fsSL -H "Authorization: Bearer ${SUPERVISOR_TOKEN}" "http://supervisor/core/api/camera_stream_source/camera.front_door_doorbell"
curl: (22) The requested URL returned error: 401
```

**Comment by felipecrs** [comment]
It's working for me as of now, with latest Home Assistant:

![image](https://github.com/felipecrs/hass-expose-camera-stream-source/assets/29582865/627a454b-b859-479c-888a-96f98286316d)

Maybe your token isn't working for some reason. Can you try rebooting your host? Also, try using a long-lived access token instead of the supervisor token, as well as the HA URL instead of the supervisor proxy.

**Comment by felipecrs** [comment]
Closing by lack of response.
