### ISSUE TITLE
connection lost

### ISSUE THREAD

**Issue by Toolmaster30** [felipecrs/hass-expose-camera-stream-source#31]
The camera loses the connection and the following appears in the Go2Rtc log:

`<html>
<body>

25.1.2024, 17:03:37 | warn | undefined error=EOF url=echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.pan_tilt_cam caller=github.com/AlexxIT/go2rtc/internal/streams/producer.go:171
-- | -- | --

</body>
</html>

`

**Comment by andonevris** [comment]
Exactly the same issue here.  Stream freezes in custom webrtc camera lovelace card after about 10 minutes with the same error, reloading the page resolves it for another 10 minutes.

`undefined error=EOF url=echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.xxxxx caller=github.com/AlexxIT/go2rtc/internal/streams/producer.go:171`

go2rtc version 1.8.5 linux/amd64
expose camera stream source 0.1.3

This is a recent issue but really hard to pin down what caused it, I have updated a lot of stuff on my HA instance, including go2rtc which is the likely candidate but like I said so many other updates I can't be sure.

**Comment by felipecrs** [comment]
There is nothing to be done in this integration, unfortunately. Please open a new issue or look for an existing one in go2rtc.

I believe that what's happening here is that Tuya stops serving the stream after 10 minutes and abruptly closes it (that's why such EOF error in go2rtc). But go2rtc does not gracefully recover the stream as it should.

It should re-request the stream URL by re-running the exec script automatically, which would in turn provide a newer and valid stream URL to go2rtc.

That's what happens when you reload the page, most likely.

**Comment by felipecrs** [comment]
@alexxit, do you think that's the case?

> I believe that what's happening here is that Tuya stops serving the stream after 10 minutes and abruptly closes it (that's why such EOF error in go2rtc). But go2rtc does not gracefully recover the stream as it should.
> 
> It should re-request the stream URL by re-running the exec script automatically, which would in turn provide a newer and valid stream URL to go2rtc.
> 
> That's what happens when you reload the page, most likely.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/issues/908

**Comment by AlexxIT** [comment]
go2rtc v1.8.5 has known bug with reconnection

**Comment by felipecrs** [comment]
Got it. Thank you!
